### ISSUE TITLE
Am I allowed to use your FoW plugin under MIT license?

### ISSUE THREAD

**Issue by RyanBram** [cityshrimp/rmmv_fow#2]
Hi, Developer. (^_^)

I really interested on your FoW plugin as it may give a great additional for our SRPG Engine system.
https://forums.rpgmakerweb.com/index.php?threads/srpg-engine-plugins-for-creating-turn-based-strategy-game.110366/

Since our project is strictly should use only MIT licensed code, may I borrow or use your plugin under MIT license to be integrated in our SRPG System?

Thank you very much for your attention.

**Comment by cityshrimp** [comment]
Hi @RyanBram,

Sure, go ahead and use my plugin.  I wrote it for a turn-base game that I wanted to write, but never finished.  Glad to hear it is useful for others :)
